version: '3'
volumes:
    config:
services:
  homeassistant:
    build: homeassistant
    ports:
      - 80:8123
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
    devices:
      - "/dev:/dev"
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
  hass-configurator:
    image: "causticlab/hass-configurator-docker:86_64"
    restart: always
    ports:
      - "8080:3218"
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
